### ISSUE TITLE
ReferenceError: mapboxgl is not defined

### ISSUE THREAD

**Issue by pyttroll** [phegman/mapbox-gl-vue.js#1]
Hi,

I followed the steps to setup the component but get a reference error whenever it's mounted.

[Vue warn]: Error in mounted hook: 
(found in <Mapbox>)

vue.esm.js?65d7:1447 ReferenceError: mapboxgl is not defined
    at VueComponent.mapInit (eval at <anonymous> (app.js:2504), <anonymous>:69:4)
    at VueComponent.boundFn [as mapInit] (eval at <anonymous> (app.js:727), <anonymous>:126:12)
    at VueComponent.mounted (eval at <anonymous> (app.js:2504), <anonymous>:58:20)
    at callHook (eval at <anonymous> (app.js:727), <anonymous>:2274:21)
    at Object.insert (eval at <anonymous> (app.js:727), <anonymous>:2953:7)
    at invokeInsertHook (eval at <anonymous> (app.js:727), <anonymous>:4959:28)
    at Vue$3.patch [as __patch__] (eval at <anonymous> (app.js:727), <anonymous>:5123:5)
    at Vue$3.Vue._update (eval at <anonymous> (app.js:727), <anonymous>:2034:19)
    at Vue$3.updateComponent (eval at <anonymous> (app.js:727), <anonymous>:2157:10)
    at Watcher.get (eval at <anonymous> (app.js:727), <anonymous>:2468:25)

Any idea what could be causing the issue?

I'm using the webpack template from vue-cli.

Thanks,

Pyt

**Comment by edanweis** [comment]
Hi, I'm getting the same error. How did you solve it?
Thanks

**Comment by phegman** [comment]
My guess is your JS script that the mapbox Vue component is in is coming before the mapbox script in your HTML file. I would suggest trying to move it below the Mapbox script. Example here:

```html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>Mapbox GL Vue JS Example</title>
        <meta name="description" content="A Vue JS component for Mapbox GL">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <script src='https://api.mapbox.com/mapbox-gl-js/v0.34.0/mapbox-gl.js'></script>
        <link href='https://api.mapbox.com/mapbox-gl-js/v0.34.0/mapbox-gl.css' rel='stylesheet' />
        <style>
			#map {
				width: 100%;
				height: 500px;
			}
        </style>
    </head>
    <body>
		<div id="app">
			<mapbox 
			access-token="your access token"
			:map-options="{
				style: 'mapbox://styles/mapbox/light-v9',
				center: [-96, 37.8],
				zoom: 3
			}"
			:geolocate-control="{
				show: true, 
				position: 'top-left'
			}"
			:scale-control="{
				show: true,
				position: 'top-left'
			}"
			:fullscreen-control="{
				show: true,
				position: 'top-left'
			}"
			@map-load="mapLoaded"
			@map-click="mapClicked"
			@map-mousemove="mapMouseMove"
			>
				
			</mapbox>
		</div><!-- /#app -->
		<script src="https://unpkg.com/vue"></script>
		<script src="/dist/app.js"></script>
    </body>
</html>
```

Notice app.js comes after mapbox-gl.js

**Comment by edanweis** [comment]
Thanks @phegman, my mistake was not including the mapbox.gl.js script at all 🥇

**Comment by phegman** [comment]
Okay, no problem! Forgot about that detail in the docs, adding it in now!

**Comment by liteultom** [comment]
Hi ! A bit late, but is there a way to use thme mapbox-gl JS files by using the mapbox-gl npm package ? I have specific requirements on a projet where I cannot use CDNs

**Comment by liteultom** [comment]
Nvm, I had to had the webpack config in the `vue.config.js` file : 

var webpack = require('webpack')
```
module.exports = {
  configureWebpack: {
    plugins: [
      new webpack.ProvidePlugin({
        mapboxgl: 'mapbox-gl'
      })
    ]
  }
}
```

**Comment by jparish3** [comment]
I tried the above but get:https://github.com/webpack/webpack/issues/4921
but none of the recommended fixes work
